import {readFile, writeFile, mkdir} from 'node:fs/promises';
const mobile='/lendet/2026-2027/mobile/';
const mcc='/lendet/2025-2026/mccc/';
const upcoming='/lendet/2026-2027/mccc/';
const archive='https://arbenl.github.io/arbenl-mobile-assignments-2025/';
const e=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const a=(url,label,secondary=false)=>`<a class="button${secondary?' secondary':''}" href="${e(url)}">${label}</a>`;
const shell=(title,content,crumb='')=>`<!doctype html><html lang="sq"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Materialet e Prof. Arben Lilës: lëndët, vitet akademike, ligjëratat dhe ushtrimet."><meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self'"><title>${title} · Arben Lila · AAB</title><link rel="stylesheet" href="/assets/catalog.css"><script src="/assets/catalog.js" defer></script></head><body><a class="skip" href="#main">Kalo te përmbajtja</a><header><div class="bar"><a class="brand" href="/"><img src="/img/aab_logo_white.png" alt="Kolegji AAB"><span>Arben Lila<br><small>Portali i lëndëve</small></span></a><nav aria-label="Navigimi kryesor"><a href="/">Lëndët & vitet</a><a href="/profesor.html">Për profesorin</a><a href="/profili.html">Profili</a></nav></div></header><main id="main">${crumb?`<nav class="crumb" aria-label="Vendndodhja"><a href="/">Lëndët</a><span> / </span>${crumb}</nav>`:''}${content}</main><footer><div>Kolegji AAB · Prof. Arben Lila · Materialet publike janë për studentët. Regjistrat e vijueshmërisë kërkojnë autentikim.</div></footer></body></html>`;
const courses=[
 {year:'2026-2027',name:'Programimi për Pajisje Mobile',key:'mobile nextjs pwa',url:mobile,status:'Në zhvillim',desc:'Nga ideja e një biznesi te një aplikacion real. Ligjëratat, ushtrimet dhe dorëzimet, javë pas jave.',ready:true},
 {year:'2026-2027',name:'Cloud Computing & MCC',key:'mccc cloud',url:upcoming,status:'Materialet ende të papublikuara',desc:'Hapësirë e veçantë për vitin e ri. Materialet dhe rezultatet e vitit të kaluar mbeten në arkivën 2025/2026.'},
 {year:'2025-2026',name:'Cloud Computing & MCC',key:'mccc cloud arkiva',url:mcc,status:'Arkivë',desc:'Syllabusi, katalogu i temave, udhëzimet, dorëzimet dhe vlerësimet për MCC 2026.'}
];
const card=c=>`<article class="card${c.ready?' featured':''}" data-course="${c.key}" data-year="${c.year}"><span class="tag">${c.year.replace('-','/')}</span><span class="tag${c.ready?' ready':''}">${c.status}</span><h2>${c.name}</h2><p>${c.desc}</p><div class="actions">${a(c.url,'Hap lëndën →')}${c.ready?a(mobile+'java-02/','Java 2',true):''}</div></article>`;
await writeFile('index.html',shell('Lëndët & vitet akademike',`<p class="eyebrow">Mëso. Ndërto. Publiko.</p><h1>Lënda jote.<br>Çdo javë, në një vend.</h1><p class="lead">Zgjidh vitin dhe lëndën. Gjej ligjëratën, ushtrimet dhe hapat e dorëzimit pa kërkuar nëpër faqe të gjata.</p><div class="toolbar"><label>Kërko lëndën<input type="search" id="search" placeholder="Mobile, Cloud, MCC…"></label><label>Viti akademik<select id="year"><option value="">Të gjitha vitet</option value="2026-2027">2026/2027</option><option value="2025-2026">2025/2026</option></select></label></div><p id="results" class="results" role="status" aria-live="polite">3 lëndë</p><div class="grid">${courses.map(card).join('')}</div><div class="section-head"><h2>Shfleto sipas vitit</h2></div><div class="actions">${a('/vitet/2026-2027/','2026/2027',true)}${a('/vitet/2025-2026/','2025/2026 · Arkiva',true)}</div>`));
for(const year of ['2026-2027','2025-2026']) {
 await mkdir(`vitet/${year}`,{recursive:true});
 await writeFile(`vitet/${year}/index.html`,shell(`Viti ${year.replace('-','/')}`,`<p class="eyebrow">Viti akademik</p><h1>${year.replace('-','/')}</h1><div class="grid">${courses.filter(c=>c.year===year).map(card).join('')}</div>`,year.replace('-','/')));
}
const plan=JSON.parse(await readFile('grading/course-plan.json','utf8'));
const manifest=JSON.parse(await readFile('materials/manifest.json','utf8'));
const weekContent=w=>w.week===1?`${a('/'+manifest.lecture1.file,'Ligjërata 1 · PPTX pa notes')}${a(mobile+'templates/Lab1_First_Win_Worksheet_45min.md','Fleta praktike',true)}${a(mobile+'syllabus.html#week-1','Përmbajtja e javës',true)}`:w.week===2?`${a('/'+manifest.lecture2.file,'Ligjërata 2 · PPTX pa notes')}${a(mobile+'java-02/prezantimi-ushtrimeve.html','Ushtrimet 2 · Në projektor',true)}${a(mobile+'java-02/','Të gjitha materialet',true)}`:`${a(mobile+'syllabus.html#week-'+w.week,'Shiko planin e javës',true)}`;
await writeFile(mobile.slice(1)+'index.html',shell('Programimi për Pajisje Mobile · 2026/2027',`<p class="eyebrow">Mobile · 2026/2027 · 15 javë</p><h1>Programimi për Pajisje Mobile</h1><p class="lead">Ndërto aplikacionin e një biznesi të vërtetë. Shembujt në ligjëratë të ndihmojnë; projekti i semestrit është i yti.</p><div class="actions">${a('#javet','Ligjëratat & ushtrimet')}${a('/attendance.html','Vijueshmëria ime',true)}${a(mobile+'dorezimet.html','Si dorëzohet detyra',true)}</div><p class="notice">Të enjten: <strong>ushtrime G1 · 14:45</strong> / <strong>ligjëratë G1 + G2 · 16:30</strong> / <strong>ushtrime G2 · 18:00</strong>. Java 1 ka vetëm ligjëratë.</p><div class="actions">${a(mobile+'java-02/kontrolli-mjeteve.html','Kontrollo mjetet e punës',true)}${a(mobile+'syllabus.html#course-overview','Syllabusi & rregullat',true)}</div><div class="section-head" id="javet"><h2>Materialet sipas javës</h2><span class="muted">Javët 1–2 kanë materiale të publikuara</span></div><div class="weeks">${plan.weeks.map(w=>`<article class="week" id="week-${w.week}"><div class="week-num">JAVA ${String(w.week).padStart(2,'0')}<br><time datetime="${w.date}">${w.date.split('-').reverse().join('.')}</time></div><div><h3>${e(w.week===2?'Nga ideja dhe skica te specifikimi dhe MVP':w.title)}</h3><p>${w.week<=2?'Materiale për studentë · pa shënimet private të profesorit':'Plan i semestrit · materialet do të publikohen këtu'}</p><div class="actions">${weekContent(w)}</div></div></article>`).join('')}</div>`,`<a href="/vitet/2026-2027/">2026/2027</a><span>/ Mobile</span>`));
const archiveLinks=[['syllabus-mcc-2026.html','Syllabusi'],['mcc-2026.html','Temat e detyrave'],['udhezime-mcc-2026.html','Udhëzimet në shqip'],['instructions-mcc-2026.html','Instructions in English'],['submissions-2026.html','Dorëzimet'],['evaluations-2026.html','Vlerësimet']];
await writeFile(mcc.slice(1)+'index.html',shell('Cloud & MCC · 2025/2026',`<p class="eyebrow">Arkivë · 2025/2026</p><h1>Cloud Computing & MCC</h1><p class="lead">Materialet dhe evidencat e MCC 2026. Këto lidhje hapin faqet ekzistuese të lëndës, me të dhënat e tyre origjinale.</p><div class="grid">${archiveLinks.map(([path,name])=>`<article class="card"><h2>${name}</h2>${a(archive+path,'Hap →')}</article>`).join('')}</div>`,`<a href="/vitet/2025-2026/">2025/2026</a><span>/ MCC</span>`));
await writeFile(upcoming.slice(1)+'index.html',shell('Cloud & MCC · 2026/2027',`<p class="eyebrow">MCCC 2026/2027</p><h1>Cloud Computing & MCC</h1><p class="lead">Hapësira e lëndës për vitin 2026/2027.</p><p class="notice">Materialet për këtë vit ende nuk janë publikuar. Kur të jenë gati, ligjëratat dhe ushtrimet do të shfaqen këtu sipas javës.</p><div class="actions">${a(mcc,'Hap arkivën MCC 2025/2026',true)}${a(mobile,'Kërkon Programimin Mobile?',true)}</div>`,`<a href="/vitet/2026-2027/">2026/2027</a><span>/ MCC</span>`));
await mkdir('mccc2026-2027',{recursive:true});
await writeFile('mccc2026-2027/index.html',`<!doctype html><html lang="sq"><head><meta charset="utf-8"><meta http-equiv="refresh" content="2;url=${upcoming}"><link rel="canonical" href="https://arbenl.github.io${upcoming}"><title>MCCC 2026/2027</title></head><body><a href="${upcoming}">Hap MCCC 2026/2027</a><script src="/assets/legacy-navigation.js" defer></script></body></html>`);
const qr=(week,kind,group)=>`https://aab-mobile-attendance.vercel.app/staff/qr?week=${week}&kind=${kind}${group?'&group='+group:''}`;
await writeFile('profesor.html',shell('Hapësira e profesorit',`<p class="eyebrow">Për profesorin</p><h1>Hap orën. Shfaq QR-në.</h1><p class="lead">Programimi për Pajisje Mobile · 2026/2027. Zgjidh javën dhe orën. Paneli i sigurt verifikon llogarinë e stafit para se të hapë regjistrimin.</p><div class="actions">${a('https://aab-mobile-attendance.vercel.app/staff','Paneli i sigurt & regjistrat')}${a(mobile,'Materialet e Mobile',true)}</div><p class="notice">Kjo është një faqe navigimi publike. QR-të dhe të dhënat e studentëve hapen vetëm pas autorizimit në shërbimin e vijueshmërisë. Shënimet private të prezantimeve nuk publikohen këtu.</p><div class="weeks">${plan.weeks.map(w=>`<article class="week"><div class="week-num">JAVA ${w.week}<br><time datetime="${w.date}">${w.date.split('-').reverse().join('.')}</time></div><div><h2>${e(w.title)}</h2><div class="actions">${w.labHours?a(qr(w.week,'lab','G1'),'QR Ushtrime G1 · 14:45',true):''}${a(qr(w.week,'lecture'),'QR Ligjëratë · 16:30')}${w.labHours?a(qr(w.week,'lab','G2'),'QR Ushtrime G2 · 18:00',true):''}</div></div></article>`).join('')}</div>`));
await writeFile('profili.html',shell('Profili i Arben Lilës',`<img class="profile" src="/img/profile.jpg" alt="Arben Lila"><p class="eyebrow">Kolegji AAB · Shkenca Kompjuterike</p><h1>Prof. Arben Lila</h1><p class="lead">Mësimdhënie në Programimin për Pajisje Mobile, Cloud Computing dhe arkitekturën e sistemeve.</p><div class="actions">${a('/','Lëndët & vitet akademike')}${a('mailto:arben.lila@universitetiaab.com','Kontakto',true)}${a(mobile+'syllabus.html#profile','Profili i plotë',true)}</div>`));
console.log('Built academic-year catalogue, course hubs and professor navigation.');
